### ISSUE TITLE
Add a more robust star background removal code

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/regularizepsf#11]
When you build a model if there is structure around the stars, you're not sampling a true delta function of PSF model; it's contaminated by the contribution of the background. We need a way of removing that. One approach is to simply make the PSF size very small and zero out the rest of the patch, but that may not always be ideal.

**Comment by sumanchapai** [comment]
Do you mean background structure, like a satellite or mere background light like moonlight?

**Comment by jmbhughes** [comment]
Yes. There could be a satellite or some background moonlight or solar corona or anything. We use stars as a measurement of the PSF, but if there are other sources interfering then you're sampling something other than just the stellar PSF. I think @svank has some ideas on this.

**Comment by sumanchapai** [comment]
If we don't already, should we also think about neighbor's influence?

**Comment by sumanchapai** [comment]
If a star has neighbor stars close to it, the PSF of that star might be intertwined to the PSF of the neighbor's that it has. Or am I misunderstanding something?

**Comment by jmbhughes** [comment]
That makes sense, especially in light of your comment in #41 that you're using this to study the M23 cluster. You're correct that if stars are particularly close they could cause issues. I believe we do **not** have any provision in the code for rejecting double stars. Some of this was taken care of in our tests because the code finds stars, centers a patch on them, and averages many such patches together. Thus, the second star in a sample gets suppressed. 

I would suggest you use [the visualization tools of regularizePSF](https://punch-mission.github.io/regularizepsf/plots.html) to double check that your PSF models are clean and not contaminated by close stars. If it is an issue, I'd be happy to help you develop a work around that rejects samples with too close neighbors.

**Comment by svank** [comment]
After #19 we should be using background-subtracted cutouts as estimated by SEP, so any smooth background should be eliminated. Sharp features like other stars or satellite tracks will still be there, but as long as there aren't too many, they should have very little effect since the estimated PSF is the median of all the cutouts. It might be pretty easy to automatically reject cutouts with other identified stars inside. Maybe non-stellar contaminants could be flagged by looking for a ~smooth radial gradient out from the center of each cutout? Would be interesting to try, but probably not necessary for most data sets. For both cases, though, if the median isn't affected much, maybe it's worth keeping those cutouts to have more samples of the core PSF?
