### ISSUE TITLE
Array vs functional model confusion.

### ISSUE THREAD

**Issue by sumanchapai** [punch-mission/regularizepsf#46]
I have a confusion in https://punch-mission.github.io/regularizepsf/quickstart.html. The article mentions about two models: "functional model or an array model." and later says that "this quickstart tutorial walks through the array model PSF model form". However, later in the "Building the target PSF" section there's the sentence "This is a functional model and is thus decorated with the simple_psf decorator". Is the word "functional" in the last sentence used in the same sense as the former? What are other possible target models?

**Comment by jmbhughes** [comment]
There are two kinds of models supported by `regularizePSF`: the functional model and the array model. Functional models are driven by a mathematical equation whereas array models are purely empirical and based on data. Both are helpful. In that quick start, you're creating an array model from some data. However, we don't just correct PSFs and instead homogenize them. I mean that we don't just undo the instrumental effects but we also impose a target PSF to make the resulting PSF in the resulting images uniform. So that little section is about setting up the target PSF from an equation (and thus it's a functional model). You can see where it's applied in `array_corrector = coordinate_patch_collection.to_array_corrector(target_evaluation)`. 

Does that answer your question? 

I'm thinking this probably isn't explained very clearly to someone unfamiliar with the transformations already. We could benefit in that quickstart from some diagrams and simpler up-front explanation before just diving into the code. I'll make it a goal to improve the documentation.

**Comment by sumanchapai** [comment]
Yep. That answers my question. It looks like we're using an array model for correction and functional model as the target model (used when building corrector).

**Comment by jmbhughes** [comment]
Exactly!
