### ISSUE TITLE
@sumanchapai initial results inquiry

### ISSUE THREAD

**Issue by sumanchapai** [punch-mission/regularizepsf#47]
<img width="680" alt="image" src="https://github.com/punch-mission/regularizepsf/assets/26862106/ab990c02-effd-48bd-a35f-a435c0b5aca2">
The image is a screenshot of our corrected FIT. I see  two things:
1. bigger patches (sized 128 * 128 it looks like)
2. smaller patches around stars (looks like sized 32).

I had use the following parameters in making the model.
```
psf_size = 32
patch_size = 256
target_fwhm = 3.25

# Define the target PSF
center = patch_size / 2
sigma = target_fwhm / 2.355
```

and 2d symmetric gaussian as the target model.

My rough understanding  is that first bigger patch is a result of applying psf function for a patch size of 128*128 and smaller one for star. I am not super clear about this and would appreciate if you could clarify or lead me to place where I could find more info regarding it.

**Comment by sumanchapai** [comment]
There are 81 patches in my `CoordinatePatchCollection` object and my image size is 1024*1024 pixels.

**Comment by jmbhughes** [comment]
For a first correction, that's not bad; I've seen worse. We can work with this and make it better. I have some ideas of what's going on, but before I speculate I'd like to see two things: 

1. An image of the data before correction
2. The extracted PSF model you built. Use code like https://punch-mission.github.io/regularizepsf/plots.html#extracted-psfs

Also, did you build the PSF model from a single image or many images?

**Comment by sumanchapai** [comment]
10 images were use to make the model.

Here's the extracted psf from original and corrected images generated using code at https://punch-mission.github.io/regularizepsf/plots.html#extracted-and-corrected-psfs

<img width="1441" alt="image" src="https://github.com/punch-mission/regularizepsf/assets/26862106/9cb69bc3-ff14-4412-af72-a4bec5c696f3">

Uncorrected image looks like:
<img width="657" alt="image" src="https://github.com/punch-mission/regularizepsf/assets/26862106/9768cf22-b5eb-4f7d-a188-ee699451c9ce">

Of course, to look at jpeg of a fits is hard and the visualization helpers help to see what's going on, and in this case the psf seems to have been enhanced.

**Comment by sumanchapai** [comment]
Correction is applied to the same 10 images that were used to generate the model.

**Comment by jmbhughes** [comment]
So I have some thoughts and things to try. Getting regularizePSF to work well on a new instrument requires some artful experimentation. You have to tweak parameters until things work. Then it should work. There are many free parameters: epsilon, alpha, psf_size, parameters of the target PSF. Then there are many other factors like the cleanliness of the background in the PSF model. I think we should work on making a guide for new users to experiment on their new datasets (and probably a FAQ) on the website. 

I would suggest trying different values of all those parameters. I've seen unclean backgrounds as the cause of the smaller boxes around stars. So you might try to modify the PSF model after its made to suppress non-stellar signal, i.e. anything below say 5% set to 0 in each window. I can help you try that. I thought that would have been dealt with our background modeling through SEP but maybe not. The vertical lines you're seeing in the PSF model and corrected image are likely some kind of Fourier ringing. 

It might be fastest to do some of this in real time on a video call. If you'd like to schedule something, we could arrange the call via email. My email is marcus.hughes@swri.org. Otherwise, we can just keep iterating here with different configurations.

**Comment by svank** [comment]
A couple of thoughts:

If you have more than these ten images available, try using many more images to build the PSF model, as that will give much better statistics. I was using hundreds of images when I used regularizepsf.

As @jmbhughes mentioned, do try varying your values of epsilon and alpha---try varying each up and down across an order or magnitude and see if you get any improvement.

**Comment by jmbhughes** [comment]
@sumanchapai please reopen this issue when you return to this project.
